version: "3.4"
services:
  arbitrum-node:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.4.0-f4bbe91
    ports:
      - 8547/tcp
      - 8548/tcp
    volumes:
      - "data:/home/user/.arbitrum/mainnet"
    environment:
      ETH1_RPC_URL: "http://geth.dappnode:8545"
      EXTRA_OPTS: ""
    image: "arbitrum-node.arbitrum.public.dappnode.eth:1.1.0"
    restart: unless-stopped
volumes:
  data: {}
